
name: Deploy Nginx to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Copy Nginx configuration to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r ./nginx-config ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/tmp/

    - name: Deploy Nginx on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
        sudo apt-get update
        sudo apt-get install -y nginx
        sudo cp -r /tmp/nginx-config/* /etc/nginx/
        sudo systemctl restart nginx
        EOF
        